# Generated by Django 5.2.3 on 2025-06-29 17:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('last_poll', models.CharField(blank=True, max_length=20, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=10, null=True)),
                ('alerts_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Hosts',
            },
        ),
        migrations.CreateModel(
            name='Polling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_interval', models.IntegerField(default=60)),
                ('history_truncate_days', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name_plural': 'Polling',
            },
        ),
        migrations.CreateModel(
            name='SmtpServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_server', models.CharField(max_length=100)),
                ('smtp_port', models.IntegerField()),
                ('smtp_sender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WebThemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=100)),
                ('theme_path', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Web Themes',
            },
        ),
        migrations.CreateModel(
            name='HostAlerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True)),
                ('host_status', models.CharField(blank=True, max_length=20, null=True)),
                ('poll_time', models.CharField(blank=True, max_length=20, null=True)),
                ('alert_cleared', models.BooleanField(default=False)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitor.hosts')),
            ],
            options={
                'verbose_name_plural': 'Host Alerts',
            },
        ),
        migrations.CreateModel(
            name='PollHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_time', models.CharField(blank=True, max_length=20, null=True)),
                ('poll_status', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_history', to='monitor.hosts')),
            ],
            options={
                'verbose_name_plural': 'Poll Histories',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerts_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
