# Generated by Django 5.2.3 on 2025-07-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='ip_address',
            field=models.CharField(max_length=21, unique=True),
        ),
    ]
