# Generated by Django 5.2.3 on 2025-07-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_hosts_ip_address_alter_hosts_previous_status_and_more'),
        ('monitor', '0003_extend_fields_for_urls'),
    ]

    operations = [
    ]
